language: php

php:
  - 5.3
  - 5.4

services:
  - mysql

env:
  - DB=mysql

before_script:
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS mwi_tests;" -uroot; fi
  - cd ~/builds
  - git clone git://github.com/JeffCost/travis.git
  - ls -la
  - mv ./travis ./mwi/bundles/travis
  - mv ./mwi/bundles/travis/tests ./mwi/application/config
  - mv ./mwi/bundles/travis/paths.php ./mwi/paths.php
  - mv ./mwi/bundles/travis/application.php ./mwi/application/config/application.php
  - echo "<?php return array('travis' => array('auto' => true));" > ./mwi/application/bundles.php
  - cd ./mwi


script:
  - php artisan travis::test:installapp
  - php artisan test thumbnails

  - php artisan test
  - php artisan test users
  - php artisan test auth
  - php artisan test admin
  - php artisan test settings
  - php artisan test themes