language: php

php:
  - 5.3
  - 5.4
  - 5.5

services:
  - mysql

env:
  - DB=mysql

before_script:
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS mwi_tests;" -uroot; fi
  - ls --color=auto
  - export CLICOLOR=1
  - git clone git://github.com/JeffCost/travis.git
  - mv ./travis ./bundles/travis
  - mv ./bundles/travis/tests ./application/config
  - mv ./bundles/travis/paths.php ./paths.php
  - mv ./bundles/travis/application.php ./application/config/application.php
  - echo "<?php return array('travis' => array('auto' => true));" > ./application/bundles.php


script:
  - php artisan travis::test:installapp
  - ./run_all_tests.sh